server:
  port: 8080

spring:
  application:
    name: realm
  profiles:
    active: dev

logging:
  config: classpath:logback-spring.xml

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true